### ISSUE TITLE
Invalid task file: Unknown task schema "envitask_3.2"

### ISSUE THREAD

**Issue by asmith26** [envi-idl/UAVToolkit#1]
Installed UAVToolkit via "Basic - PRO code" method.

IDL = v8.6.1
ENVI = v5.4.1

Running [the initial "Usage" commands](https://github.com/envi-idl/UAVToolkit#usage) in an IDL console, I get the error:

```
ENVI> uav_toolkit
% ENVITASK: Invalid task file: Unknown task schema "envitask_3.2". 
% Execution halted at:  ENVITASK           56  
%                       UAV_TOOLKIT       135 Path\to\UAVToolkit\uav_toolkit.pro
%                       $MAIN
```

Many thanks for any help in advance

**Comment by znorman-harris** [comment]
@asmith26 sorry for the delay in getting back to you - this is because you will need to have ENVI 5.5 and IDL 8.7 for this repository. That is listed under the Requirements section of the README.md which could probably be easier to find, so I'll move that towards the top.

**Comment by asmith26** [comment]
I see and no problem - thanks for getting back to me
